# Урок 6

In [1]:
import numpy as np

__1.__ Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

### Решение

<img src="images\IMG_20200408_0004.jpg">

__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    
   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

### Решение

In [20]:
def check_matrix(A, B):
    r_a = np.linalg.matrix_rank(A)
    A_ = np.hstack((A, B))
    r_a_ = np.linalg.matrix_rank(A_)
    n = np.shape(A)[1]
    
    print(A_)
    if r_a == r_a_ and r_a == n:
        print("Система совместна и имеет единственное решение")
    elif r_a == r_a_ and r_a < n:
        print("Система совместна и имеет бесконечное количество решений")
    elif r_a < r_a_:
        print("Система несовместна")
    else:
        print("Такого не может быть")
    
    
print("a)")
A = np.array([[3, -1, 1], 
              [2, -5, -3],
              [1, 1, -1]])
B = np.array([[4], 
              [-17],
              [0]])
check_matrix(A, B)

print("б)")
A = np.array([[2, -4, 6], 
              [1, -2, 3],
              [3, -6, 9]])
B = np.array([[1], 
              [-2],
              [5]])
check_matrix(A, B)

print("в)")
A = np.array([[1, 2, 5], 
              [3, 1, -8]])
B = np.array([[4], 
              [-2]])
check_matrix(A, B)

a)
[[  3  -1   1   4]
 [  2  -5  -3 -17]
 [  1   1  -1   0]]
Система совместна и имеет единственное решение
б)
[[ 2 -4  6  1]
 [ 1 -2  3 -2]
 [ 3 -6  9  5]]
Система несовместна
в)
[[ 1  2  5  4]
 [ 3  1 -8 -2]]
Система совместна и имеет бесконечное количество решений


__3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

### Решение

In [21]:
A = np.array([[1, 3, -2, 4], 
              [0, 5, 0, 1],
              [0, 0, 3, 0],
              [0, 0, 0, 2]])
B = np.array([[3], 
              [2],
              [4],
              [1]])
check_matrix(A, B)

[[ 1  3 -2  4  3]
 [ 0  5  0  1  2]
 [ 0  0  3  0  4]
 [ 0  0  0  2  1]]
Система совместна и имеет единственное решение


__4.__ Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

### Решение

<img src="images\IMG_20200408_0003.jpg">