# Урок 5

In [1]:
import numpy as np

__1.__ Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$

### Решение:

In [2]:
np.set_printoptions(precision=2, suppress=True)
a = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1 -6]
 [ 2  6]]
Собственные значения:
[2. 3.]
Собственные векторы:
[[-0.89  0.83]
 [ 0.45 -0.55]]


__2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей 

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Показать, что __любой__ вектор является для него собственным.

### Решение:

In [26]:
a = np.array([[-1, 0], [0, -1]])
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1  0]
 [ 0 -1]]
Собственные значения:
[-1. -1.]
Собственные векторы:
[[1. 0.]
 [0. 1.]]


In [28]:
# Проверим на значениях от 0 до 999
find = False
for i in range(1000):
    for j in range(1000):
        if any(a @ np.array([i, j]) != w[0] * np.array([i, j])):
            find = True
            break
        if find == True:
            break
if find == True:
    print('Найден не собственный вектор')
else:
    print('Все векторы собственные')

Все векторы собственные


__3.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.

### Решение:

In [38]:
a = np.array([[1, 1], [-1, 3]])
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[ 1  1]
 [-1  3]]
Собственные значения:
[2. 2.]
Собственные векторы:
[[ 0.71 -0.71]
 [ 0.71 -0.71]]


In [40]:
x = np.array([1, 1])
a @ x / x

array([2., 2.])

Получили $\lambda$ = 2. Вектор собственный.

__4.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

### Решение:

In [34]:
a = np.array([[0, 3, 0], [3, 0, 0], [0, 0, 3]])
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[0 3 0]
 [3 0 0]
 [0 0 3]]
Собственные значения:
[ 3. -3.  3.]
Собственные векторы:
[[ 0.71 -0.71  0.  ]
 [ 0.71  0.71  0.  ]
 [ 0.    0.    1.  ]]


In [36]:
x = np.array([3, -3, -4])
a @ x / x

array([-3., -3.,  3.])

Значения $\lambda$ приняли разные значения. Вектор не собственный.